### PR TITLE
Zf24

### PR DESCRIPTION
**Pull request by Rastusik**
Hi Matthieu, I tried to fix the php di zf2 integration using the newest zf2 (2.4). Feel free to merge the code into the main branch, if it is good enough.

Just for the record - it might be a good idea to update the packagist configuration, since it even doesn't point to the current newest commit in the current master branch.

### CODE REVIEW

**Comment by mnapoli** [comment]
Hey thanks a lot, I am coming back from holidays so I'll have a look in the next days, but this is much welcome as I don't use ZF2 myself.

**Comment by mnapoli** [comment]
A question: have you been able to use it with your changes and check it works? On my end I have no way to ensure that (I don't use ZF2). Another solution would be to add a little test or demo application but I don't have much time, I don't know about you.

**Comment by Rastusik** [comment]
yes, I have tested it ... I will upload a demo app, maybe today, maybe during the weekend

**Comment by Rastusik** [comment]
so, the demo app is here: https://github.com/Rastusik/ZendSkeletonApplication/tree/php-di-integration-test

to test it, you have to clone it, and then:
php composer.phar update -o
cd public
php -S localhost:11000

and visit http://localhost:11000/hello

Check out the GreetingController class to see the @Inject annotation working

**Comment by mnapoli** [comment]
OK this is awesome, thank you for doing this. Would you be interested to be the maintainer of this repository? What I think would be great would be:

- I merge this pull request
- I add you as maintainer
- you can push the ZendSkeletonApplication into this repository in a directory (just like for the ZF1 integration there's the `quickstart/` repository, see https://github.com/PHP-DI/ZF1-Bridge)
- you tag a stable `1.0.0` release
- then I can update PHP-DI's documentation to say that this "ZF2 - PHP-DI integration" is no longer in beta and is working fine

What do you think?

**Comment by Rastusik** [comment]
Well, to be honest, I could do all the things you suggested, but I'm not so sure about the maintainer position, since I cannot guarantee any spare time for the work for now. How time consuming would it be?

**Comment by mnapoli** [comment]
I don't think there is much to do (I've never seen a bug open here), it's basically letting you push directly into the repository if you need to fix anything or want to improve anything. No obligation to anything ;)

**Comment by Rastusik** [comment]
Ok, so I pushed the quickstart code into the zf24 branch, now it's your turn :) Also, if there are no obligations or anything else, I can try the maintainer role, let's see where this goes :)

**Comment by mnapoli** [comment]
Awesome, I've invited you for push access to this repository feel free to merge this pull request and release!

**Comment by Rastusik** [comment]
Cool. I have just created the 1.0.0 release. Is that all for now? Is there no other work to be done on packagist.org? I'm just asking, because I haven't done much work with packagist and with version releases yet.

**Comment by mnapoli** [comment]
Yep it seems all good, the version is showing up on Packagist: https://packagist.org/packages/php-di/zf2-bridge

Cool!

**Pull request merged**
